# Generated by Django 4.2.18 on 2025-08-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='products/')),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
